import { GoogleGenAI, Type } from "@google/genai";
import type { AiResultSource, AiTaskResult } from "@/lib/ai/types";
import { fetchFreeResearchSources, type FreeResearchSource } from "@/lib/ai/free-web-research";

type GeminiRunOptions={systemPrompt:string;userPrompt:string;useWebSearch:boolean};
function boundedInteger(value:string|undefined,fallback:number,min:number,max:number){const n=Number(value);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.round(n))):fallback;}
function validateResult(value:unknown):AiTaskResult{if(!value||typeof value!=="object")throw new Error("Gemini 결과가 JSON 객체가 아닙니다.");const r=value as Record<string,unknown>;if(typeof r.title!=="string"||typeof r.summary!=="string"||typeof r.body!=="string"||typeof r.confidence!=="number"||typeof r.needs_human_review!=="boolean"||!Array.isArray(r.sources))throw new Error("Gemini 결과 구조가 SAWOL OFFICE Schema와 다릅니다.");return {title:r.title.trim(),summary:r.summary.trim(),body:r.body.trim(),confidence:Math.max(0,Math.min(100,Math.round(r.confidence))),needs_human_review:r.needs_human_review,sources:(r.sources as any[]).map(x=>({title:typeof x?.title==="string"?x.title.trim():"",url:typeof x?.url==="string"?x.url.trim():"",note:typeof x?.note==="string"?x.note.trim():""})).filter(Boolean)};}
function retryable(error:unknown){const m=error instanceof Error?error.message:String(error??"");return m.includes('"code":429')||m.includes('"code":503')||m.includes("RESOURCE_EXHAUSTED")||m.includes("UNAVAILABLE")||m.toLowerCase().includes("high demand");}
async function withRetry<T>(fn:()=>Promise<T>){const delays=[0,1500,3500];let last:unknown;for(let i=0;i<delays.length;i++){if(delays[i])await new Promise(r=>setTimeout(r,delays[i]));try{return await fn();}catch(e){last=e;if(!retryable(e)||i===delays.length-1)throw e;}}throw last;}
function researchContext(rows:FreeResearchSource[]){return `[무료 실시간 검색 근거]\n아래는 SAWOL OFFICE가 방금 수집한 실제 뉴스 검색 결과입니다. 존재하지 않는 기사·언론사·링크를 만들지 마세요. 요청 수량에 맞는 항목을 이 목록에서 선별하세요.\n\n${rows.map((x,i)=>`${i+1}. ${x.title}\n- 언론사: ${x.source}\n- 발행시각: ${x.published_at||"확인 필요"}\n- 링크: ${x.url}`).join("\n\n")}`;}
function sanitizeSources(model:AiResultSource[],rows:FreeResearchSource[]){if(!rows.length)return model;const allowed=new Map(rows.map(x=>[x.url,x]));const verified=model.flatMap(x=>{const m=allowed.get(x.url);return m?[{title:m.title,url:m.url,note:`${m.source} · ${m.published_at||"발행시각 확인 필요"}`}]:[];});return verified.length?verified:rows.slice(0,5).map(x=>({title:x.title,url:x.url,note:`${x.source} · ${x.published_at||"발행시각 확인 필요"}`}));}
export async function runGeminiTask({systemPrompt,userPrompt,useWebSearch}:GeminiRunOptions){const apiKey=process.env.GEMINI_API_KEY;if(!apiKey)throw new Error("GEMINI_API_KEY가 설정되어 있지 않습니다. .env.local을 확인해주세요.");const model=process.env.GEMINI_MODEL||"gemini-3.5-flash-lite";const maxOutputTokens=boundedInteger(process.env.GEMINI_MAX_OUTPUT_TOKENS,7000,1000,20000);const rows=useWebSearch?await fetchFreeResearchSources(userPrompt,12):[];if(useWebSearch&&!rows.length)throw new Error("최신 정보 검색이 필요한 업무인데 무료 검색 결과를 가져오지 못했습니다. 잠시 후 다시 시도해주세요.");const ai=new GoogleGenAI({apiKey});const response=await withRetry(()=>ai.models.generateContent({model,contents:rows.length?`${userPrompt}\n\n${researchContext(rows)}`:userPrompt,config:{systemInstruction:systemPrompt,temperature:useWebSearch?0.15:0.35,maxOutputTokens,responseMimeType:"application/json",responseSchema:{type:Type.OBJECT,properties:{title:{type:Type.STRING},summary:{type:Type.STRING},body:{type:Type.STRING},confidence:{type:Type.INTEGER},needs_human_review:{type:Type.BOOLEAN},sources:{type:Type.ARRAY,items:{type:Type.OBJECT,properties:{title:{type:Type.STRING},url:{type:Type.STRING},note:{type:Type.STRING}},required:["title","url","note"]}}},required:["title","summary","body","confidence","needs_human_review","sources"]}}}));const raw=response.text?.trim();if(!raw)throw new Error("Gemini 응답에 결과 텍스트가 없습니다.");let parsed:unknown;try{parsed=JSON.parse(raw);}catch{throw new Error("Gemini Structured Output을 JSON으로 해석하지 못했습니다.");}const result=validateResult(parsed);result.sources=sanitizeSources(result.sources,rows);if(useWebSearch&&!result.sources.length)result.needs_human_review=true;return {provider:"gemini",model,responseId:null,usage:response.usageMetadata??null,result,usedWebSearch:rows.length>0,requestedWebSearch:Boolean(useWebSearch)};}
