"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export function ApprovalTaskActions({taskId,executionMode="MANUAL"}:{taskId:string;executionMode?:"AUTO"|"MANUAL"}){
 const router=useRouter(); const [busy,setBusy]=useState<"approve"|"reject"|null>(null); const [message,setMessage]=useState(""); const [open,setOpen]=useState(false); const [reason,setReason]=useState("");
 async function approve(){if(busy)return;setBusy("approve");setMessage("");const supabase=createClient();const {data,error}=await supabase.rpc("sawol_finalize_task_approval",{p_task_id:taskId});if(error){setMessage("승인 완료 처리에 실패했습니다. "+error.message);setBusy(null);return;}if((data as any)?.artifacts?.has_result===false)setMessage("업무는 완료됐지만 연결된 실행 결과가 없어 결과함/기억센터에는 생성되지 않았습니다.");await supabase.from("task_feedback").update({status:"RESOLVED",resolved_at:new Date().toISOString()}).eq("root_task_id",taskId).eq("status","ACTIVE");router.refresh();setBusy(null);}
 async function reject(){if(busy||!reason.trim())return;setBusy("reject");setMessage("");const supabase=createClient();const {error}=await supabase.rpc("sawol_reject_autonomous_task",{p_root_task_id:taskId,p_reason:reason.trim()});if(error){const missing=error.message.includes("sawol_reject_autonomous_task");setMessage(missing?"반려용 DB 함수가 아직 적용되지 않았습니다. STEP22 재정비 SQL을 먼저 실행해주세요.":"반려 처리에 실패했습니다. "+error.message);setBusy(null);return;}setOpen(false);setReason("");if(executionMode==="AUTO"){try{for(let i=0;i<12;i++){const r=await fetch(`/api/office/tasks/${taskId}/autopilot`,{method:"POST"});const p=await r.json().catch(()=>null);if(!r.ok||!p?.ok)throw new Error(p?.message||"재작업 실행 실패");if(p.state==="AWAITING_APPROVAL")break;}}catch(e){setMessage(`반려는 접수됐지만 자동 재작업 중 오류가 발생했습니다. ${e instanceof Error?e.message:""}`);}}else{setMessage("반려 사유를 저장하고 수동 업무를 대기 상태로 되돌렸습니다. 업무 상세에서 직접 수정·재실행해주세요.");}router.refresh();setBusy(null);}
 return <div><div className="flex flex-col gap-2 sm:flex-row"><button disabled={busy!==null} onClick={approve} className="h-10 rounded-[10px] bg-[#17181C] px-4 text-[11px] font-semibold text-white disabled:opacity-50">{busy==="approve"?"결과 정리 중...":"승인 후 완료"}</button><button disabled={busy!==null} onClick={()=>setOpen(true)} className="h-10 rounded-[10px] border border-[#F0D2D2] bg-white px-4 text-[11px] font-semibold text-[#B14444] disabled:opacity-50">반려 · 수정 요청</button></div>{message?<p className="mt-2 max-w-[420px] rounded-[9px] bg-[#FFF7E8] px-3 py-2 text-[10px] leading-5 text-[#8A6824]">{message}</p>:null}
 {open?<div className="fixed inset-0 z-[150] flex items-center justify-center bg-black/30 p-4 backdrop-blur-[2px]"><div className="w-full max-w-[520px] rounded-[20px] bg-white p-5 shadow-2xl sm:p-6"><p className="text-[11px] font-semibold text-[#B14444]">대표 반려</p><h2 className="mt-1 text-[18px] font-semibold">어떤 부분을 수정할까요?</h2><p className="mt-2 text-[10px] leading-5 text-[#7A808B]">사유를 적으면 비서실장이 관련 단계를 다시 열고 필요한 AI 직원들이 자동으로 재작업한 뒤 새 최종본을 승인함에 올립니다.</p><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="예: 전체 구성은 좋은데 타깃 설명이 약하고 문구가 너무 광고 같아. 그 부분을 수정해줘." className="mt-4 min-h-[130px] w-full resize-y rounded-[12px] border border-[#E1E4E9] p-3 text-[11px] leading-5 outline-none focus:border-[#3157D5]"/><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>{if(!busy)setOpen(false)}} className="h-11 rounded-[10px] border border-[#E1E4E9] text-[11px] font-semibold">취소</button><button onClick={reject} disabled={busy!==null||!reason.trim()} className="h-11 rounded-[10px] bg-[#B14444] text-[11px] font-semibold text-white disabled:opacity-40">{busy==="reject"?"재작업 지시 중...":"반려하고 자동 재작업"}</button></div></div></div>:null}</div>;
}
